"""empty message

Revision ID: 234764cc0996
Revises: 1717a97ac71e
Create Date: 2025-09-16 14:45:01.618706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '234764cc0996'
down_revision = '1717a97ac71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ChatGroup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('ChatGroup_chatId_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ChatGroup_panelId_fkey'), type_='foreignkey')
        batch_op.drop_column('chat_at')
        batch_op.drop_column('chatId')
        batch_op.drop_column('panelId')

    with op.batch_alter_table('UserChat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupID', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_userchat_group'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ChatGroup', ['groupID'], ['id'])
        batch_op.drop_column('groupId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserChat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_userchat_group'), 'ChatGroup', ['groupId'], ['id'])
        batch_op.drop_column('groupID')

    with op.batch_alter_table('ChatGroup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panelId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('chatId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chat_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('ChatGroup_panelId_fkey'), 'UserPanel', ['panelId'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ChatGroup_chatId_fkey'), 'UserChat', ['chatId'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
