"""empty message

Revision ID: 4b9e6b83e2f9
Revises: 766381d5badd
Create Date: 2025-09-16 10:05:45.651836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9e6b83e2f9'
down_revision = '766381d5badd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserChat', schema=None) as batch_op:
        batch_op.alter_column('recieverID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserChat', schema=None) as batch_op:
        batch_op.alter_column('recieverID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
