"""empty message

Revision ID: 766381d5badd
Revises: 
Create Date: 2025-09-15 14:38:00.968584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766381d5badd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('UserPanel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserChat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panelID', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('recieverID', sa.Integer(), nullable=False),
    sa.Column('chat', sa.String(length=255), nullable=False),
    sa.Column('chat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['panelID'], ['UserPanel.id'], ),
    sa.ForeignKeyConstraint(['recieverID'], ['User.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChatGroup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatTitle', sa.String(length=255), nullable=False),
    sa.Column('chatId', sa.Integer(), nullable=False),
    sa.Column('panelId', sa.Integer(), nullable=False),
    sa.Column('chat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['UserChat.id'], ),
    sa.ForeignKeyConstraint(['panelId'], ['UserPanel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ChatGroup')
    op.drop_table('UserChat')
    op.drop_table('UserPanel')
    op.drop_table('User')
    op.drop_table('Admin')
    # ### end Alembic commands ###
